# Generated by Django 5.2.3 on 2025-07-24 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='makestaffsalary',
            options={'verbose_name': 'Maosh tayinlash', 'verbose_name_plural': 'Maoshlar tayinlash'},
        ),
    ]
