# Generated by Django 5.2.3 on 2025-07-24 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_makestaffsalary_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmodel',
            name='education_center',
        ),
    ]
