# Generated by Django 5.2.3 on 2025-07-24 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_staffmodel_education_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmodel',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='staffmodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='staffmodel',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='staffmodel',
            name='third_name',
        ),
    ]
