# Generated by Django 5.1.6 on 2025-07-26 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_staffmodel_bio_remove_staffmodel_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='ducation_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.edumodel'),
        ),
    ]
