# Generated by Django 5.1.6 on 2025-07-26 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_paymentmodel_ducation_center'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmodel',
            old_name='ducation_center',
            new_name='education_center',
        ),
    ]
