# Generated by Django 5.1.6 on 2025-07-26 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_ducation_center_paymentmodel_education_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmodel',
            name='education_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.edumodel'),
        ),
    ]
